In [1]:
## Reading From init file
from mysql_connect import MySqlConnection
import json

In [2]:
budget_schema_config = {
    "host":"127.0.0.1",
    "user":"analysis",
    "database":'myhr'
}

mysql_conn = MySqlConnection(**budget_schema_config)
mysql_conn.connect()

MySql Connection Details:
Data Base --> myhr
User --> analysis@localhost
Date Time --> 2024-12-28 08:17:10 PM

In [3]:
employee_df  = mysql_conn.table_query("Select * from employees")
employee_df

,employee_id,first_name,last_name,email,phone_number,hire_date,job_id,salary,manager_id,department_id
0,100,Steven,King,steven.king@sqltutorial.org,515.123.4567,1987-06-17,4,24000.00,NaN,9
1,101,Neena,Kochhar,neena.kochhar@sqltutorial.org,515.123.4568,1989-09-21,5,17000.00,100.0,9
2,102,Lex,De Haan,lex.de haan@sqltutorial.org,515.123.4569,1993-01-13,5,17000.00,100.0,9
3,103,Alexander,Hunold,alexander.hunold@sqltutorial.org,590.423.4567,1990-01-03,9,9000.00,102.0,6
4,104,Bruce,Ernst,bruce.ernst@sqltutorial.org,590.423.4568,1991-05-21,9,6000.00,103.0,6
5,105,David,Austin,david.austin@sqltutorial.org,590.423.4569,1997-06-25,9,4800.00,103.0,6
6,106,Valli,Pataballa,valli.pataballa@sqltutorial.org,590.423.4560,1998-02-05,9,4800.00,103.0,6
7,107,Diana,Lorentz,diana.lorentz@sqltutorial.org,590.423.5567,1999-02-07,9,4200.00,103.0,6
8,108,Nancy,Greenberg,nancy.greenberg@sqltutorial.org,515.124.4569,1994-08-17,7,12000.00,101.0,10
9,109,Daniel,Faviet,daniel.faviet@sqltutorial.org,515.124.4169,1994-08-16,6,9000.00,108.0,10
10,110,John,Chen,john.chen@sqltutorial.org,515.124.4269,1997-09-28,6,8200.00,108.0,10
11,111,Ismael,Sciarra,ismael.sciarra@sqltutorial.org,515.124.4369,1997-09-30,6,7700.00,108.0,10
12,112,Jose Manuel,Urman,jose manuel.urman@sqltutorial.org,515.124.4469,1998-03-07,6,7800.00,108.0,10
13,113,Luis,Popp,luis.popp@sqltutorial.org,515.124.4567,1999-12-07,6,6900.00,108.0,10
14,114,Den,Raphaely,den.raphaely@sqltutorial.org,515.127.4561,1994-12-07,14,11000.00,100.0,3
15,115,Alexander,Khoo,alexander.khoo@sqltutorial.org,515.127.4562,1995-05-18,13,3100.00,114.0,3
16,116,Shelli,Baida,shelli.baida@sqltutorial.org,515.127.4563,1997-12-24,13,2900.00,114.0,3
17,117,Sigal,Tobias,sigal.tobias@sqltutorial.org,515.127.4564,1997-07-24,13,2800.00,114.0,3
18,118,Guy,Himuro,guy.himuro@sqltutorial.org,515.127.4565,1998-11-15,13,2600.00,114.0,3
19,119,Karen,Colmenares,karen.colmenares@sqltutorial.org,515.127.4566,1999-08-10,13,2500.00,114.0,3
20,120,Matthew,Weiss,matthew.weiss@sqltutorial.org,650.123.1234,1996-07-18,19,8000.00,100.0,5
21,121,Adam,Fripp,adam.fripp@sqltutorial.org,650.123.2234,1997-04-10,19,8200.00,100.0,5
22,122,Payam,Kaufling,payam.kaufling@sqltutorial.org,650.123.3234,1995-05-01,19,7900.00,100.0,5
23,123,Shanta,Vollman,shanta.vollman@sqltutorial.org,650.123.4234,1997-10-10,19,6500.00,100.0,5
24,126,Irene,Mikkilineni,irene.mikkilineni@sqltutorial.org,650.124.1224,1998-09-28,18,2700.00,120.0,5
25,145,John,Russell,john.russell@sqltutorial.org,None,1996-10-01,15,14000.00,100.0,8
26,146,Karen,Partners,karen.partners@sqltutorial.org,None,1997-01-05,15,13500.00,100.0,8
27,176,Jonathon,Taylor,jonathon.taylor@sqltutorial.org,None,1998-03-24,16,8600.00,100.0,8
28,177,Jack,Livingston,jack.livingston@sqltutorial.org,None,1998-04-23,16,8400.00,100.0,8
29,178,Kimberely,Grant,kimberely.grant@sqltutorial.org,None,1999-05-24,16,7000.00,100.0,8
30,179,Charles,Johnson,charles.johnson@sqltutorial.org,None,2000-01-04,16,6200.00,100.0,8
31,192,Sarah,Bell,sarah.bell@sqltutorial.org,650.501.1876,1996-02-04,17,4000.00,123.0,5
32,193,Britney,Everett,britney.everett@sqltutorial.org,650.501.2876,1997-03-03,17,3900.00,123.0,5
33,200,Jennifer,Whalen,jennifer.whalen@sqltutorial.org,515.123.4444,1987-09-17,3,4400.00,101.0,1
34,201,Michael,Hartstein,michael.hartstein@sqltutorial.org,515.123.5555,1996-02-17,10,13000.00,100.0,2
35,202,Pat,Fay,pat.fay@sqltutorial.org,603.123.6666,1997-08-17,11,6000.00,201.0,2
36,203,Susan,Mavris,susan.mavris@sqltutorial.org,515.123.7777,1994-06-07,8,6500.00,101.0,4
37,204,Hermann,Baer,hermann.baer@sqltutorial.org,515.123.8888,1994-06-07,12,10000.00,101.0,7
38,205,Shelley,Higgins,shelley.higgins@sqltutorial.org,515.123.8080,1994-06-07,2,12000.00,101.0,11
39,206,William,Gietz,william.gietz@sqltutorial.org,515.123.8181,1994-06-07,1,8300.00,205.0,11

In [4]:
mysql_conn.connection_close()

MySql Connection Closed.........

In [5]:
from db_json import Database

In [6]:
test = Database()

In [7]:
import os
from pathlib import Path

In [8]:
dirr = Path(os.getcwd())
dirr

WindowsPath('d:/ML_NOTE/Python/API/Flask_Website_campusx')

In [144]:
import hashlib

In [177]:
def insert(name, email, password):
    if os.path.exists('users.json'):
        with open('users.json', 'r') as rf:
            users = json.load(rf)

        if email in users:
            print(f"{email} Present")
        else:
            hashed_password = hashlib.sha256(password.encode()).hexdigest()
            users[email] = [name, hashed_password]
        
        with open('users.json','w') as wf:
            json.dump(users, wf, indent=4)
    else:
        users = {}
        hashed_password = hashlib.sha256(password.encode()).hexdigest()
        users[email] = [name, hashed_password] 
        with open('users.json', 'w') as wf: 
            json.dump(users, wf, indent=4)

def authenticate(email, password): 
    if os.path.exists('users.json'): 
        with open('users.json', 'r') as rf: 
            users = json.load(rf) 
            if email in users:
                print(users[email] )
                stored_name, stored_hashed_password = users[email] 
                hashed_password = hashlib.sha256(password.encode()).hexdigest() 
                if hashed_password == stored_hashed_password: 
                    return 1 
                return 0
            else:
                return 0

In [175]:
name = 'Nareshdddd'
email = 'nnnnngmail.com'
password = 'ttttt'
insert(name, email, password)

nnnnngmail.com Present

In [178]:
authenticate(email, password)

['Nareshdddd', '37c9aa3186e19d9e3cfb4f2ec195d3a3ba27e280be967bda536828003c94a0d2']

1

In [182]:
class Database:

    def insert(self,name, email, password):
        """Insert Register Credential"""
        if os.path.exists('users.json'):
            with open('users.json', 'r') as rf:
                users = json.load(rf)

            if email in users:
                return 0
            else:
                hashed_password = hashlib.sha256(password.encode()).hexdigest()
                users[email] = [name, hashed_password]
            
            with open('users.json','w') as wf:
                json.dump(users, wf, indent=4)
                return 1
        else:
            users = {}
            hashed_password = hashlib.sha256(password.encode()).hexdigest()
            users[email] = [name, hashed_password] 
            with open('users.json', 'w') as wf: 
                json.dump(users, wf, indent=4)
                return 1
            
    def authenticate(self,email, password): 
        """Authenticate Login Credential"""
        if os.path.exists('users.json'): 
            with open('users.json', 'r') as rf: 
                users = json.load(rf) 
                if email in users: 
                    stored_name, stored_hashed_password = users[email] 
                    hashed_password = hashlib.sha256(password.encode()).hexdigest() 
                    if hashed_password == stored_hashed_password: 
                        return True 
                    return False 
                return False

In [183]:
dbo = Database()

In [ ]:
name = 'Naresh'
email = 'naresh@gmail.com'
password = 'naresh'
dbo.insert(name, email, password)

In [187]:
dbo.authenticate(email,password)

False

In [6]:
import calendar
from datetime import datetime

def highlight_today():
    # Get today's date
    today = datetime.today()
    year = today.year
    month = today.month
    day = today.day
    print(day)
    # Create a plain text calendar
    cal = calendar.TextCalendar(calendar.MONDAY)
    cal_str = cal.formatmonth(year, month)

    # Highlight today's date
    cal_str = cal_str.replace(f'{day} ', f'[{day}]')

    return cal_str

# Print the calendar with today's date highlighted
print(highlight_today())

30
   December 2024
Mo Tu We Th Fr Sa Su
                   1
 2  3  4  5  6  7  8
 9 10 11 12 13 14 15
16 17 18 19 20 21 22
23 24 25 26 27 28 29
[30]31

In [1]:
from constant import question
import os 
import json 

category_var = {}
for key, value in question.items():
    category_var[key] = {}
    for k , v in value.items():
        for kk, vv in v.items():
            key_name = str(k)+'_'+kk
            category_var[key][key_name] = vv
category_var

file = 'questions.json'
if os.path.exists(file):
    os.remove(file)

with open(file,'w') as wf:
    json.dump(category_var, wf, indent=4)

In [2]:
import json
with open (file,'r') as rf:
    response = json.load(rf)
    print(response.keys())

dict_keys(['ml_interview_questions_and_answers', 'dl_interview_questions_and_answers', 'python_question', 'mlops'])

In [3]:
cat_name = {
    'machine_learning':'ml_interview_questions_and_answers',
    'deep_learning':'dl_interview_questions_and_answers',
    'python':'python_question',
    'mlops': 'mlops'
}

In [18]:
category = 'machine_learning'

In [45]:
class QuestionAnswer:

    def cat_name_var (self,category):
        cat_name_var = {
                        'machine_learning':'ml_interview_questions_and_answers',
                        'deep_learning':'dl_interview_questions_and_answers',
                        'python':'python_question',
                        'mlops': 'mlops'
                        }
        return cat_name_var[category]
    

    def get_question_answer(self,category):
        with open ('questions.json','r') as rf:
            response = json.load(rf)
            category_key = self.cat_name_var(category)
            result = response[category_key]
            sorted_result = {k: result[k] for k in sorted(result)}
            return sorted_result

In [46]:
qa = QuestionAnswer()
qa.get_question_answer(category)

{'10_answer': 'An algorithm is a step-by-step procedure for solving a problem, while a model is a specific instance of an algorithm trained on data to perform a task.',
 '10_question': 'What is the difference between a model and an algorithm?',
 '11_answer': 'Bagging involves training multiple models in parallel on different subsets of the data and averaging their predictions, while boosting trains models sequentially, each one focusing on the mistakes of the previous ones.',
 '11_question': 'What is the difference between bagging and boosting?',
 '12_answer': 'A confusion matrix is a table that describes the performance of a classification model by showing the true positive, true negative, false positive, and false negative predictions.',
 '12_question': 'What is a confusion matrix and how is it used?',
 '13_answer': 'Regularization is a technique used to prevent overfitting by adding a penalty to the loss function for large coefficients, thus encouraging simpler models. Common regularization techniques include L1 and L2 regularization.',
 '13_question': 'What is regularization and why is it useful?',
 '14_answer': "A Receiver Operating Characteristic (ROC) curve is a graphical representation of a classification model's performance by plotting the true positive rate against the false positive rate at various threshold settings.",
 '14_question': 'What is a ROC curve?',
 '15_answer': 'Parametric models have a fixed number of parameters and make strong assumptions about the data distribution, while non-parametric models have a flexible number of parameters and make fewer assumptions about the data.',
 '15_question': 'What is the difference between parametric and non-parametric models?',
 '16_answer': 'The learning rate controls the size of the steps taken towards the minimum of the loss function in gradient descent. A small learning rate may result in slow convergence, while a large learning rate may cause divergence.',
 '16_question': 'What is the purpose of the learning rate in gradient descent?',
 '17_answer': 'Ensemble learning is a technique that combines multiple models to improve overall performance. Common ensemble methods include bagging, boosting, and stacking.',
 '17_question': 'What is ensemble learning?',
 '18_answer': 'The validation set is used to evaluate the performance of a model during training and to tune hyperparameters. It helps to avoid overfitting by providing an unbiased evaluation of the model.',
 '18_question': 'What is the purpose of the validation set?',
 '19_answer': 'Generative models learn the joint probability distribution of the input and output, while discriminative models learn the conditional probability distribution of the output given the input.',
 '19_question': 'What is the difference between a generative and a discriminative model?',
 '1_answer': 'Supervised learning involves training a model on labeled data, while unsupervised learning involves finding patterns in unlabeled data.',
 '1_question': 'What is the difference between supervised and unsupervised learning?',
 '20_answer': 'The curse of dimensionality refers to the challenges and difficulties that arise when analyzing and organizing data in high-dimensional spaces, where the volume of the space increases exponentially with the number of dimensions.',
 '20_question': 'What is the curse of dimensionality?',
 '21_answer': 'A support vector machine (SVM) is a supervised learning model used for classification and regression tasks. It works by finding the hyperplane that best separates the data points of different classes.',
 '21_question': 'What is a support vector machine (SVM)?',
 '22_answer': 'A decision tree is a supervised learning algorithm used for classification and regression tasks. It splits the data into subsets based on the value of input features and makes decisions in a tree-like structure.',
 '22_question': 'What is a decision tree?',
 '23_answer': 'k-nearest neighbors (k-NN) is a supervised learning algorithm used for classification and regression tasks. It classifies a data point based on the majority class of its k-nearest neighbors.',
 '23_question': 'What is k-nearest neighbors (k-NN)?',
 '24_answer': 'Bagging involves training multiple models in parallel on different subsets of the data and averaging their predictions, while boosting trains models sequentially, each one focusing on the mistakes of the previous ones.',
 '24_question': 'What is the difference between bagging and boosting?',
 '25_answer': 'A confusion matrix is a table that describes the performance of a classification model by showing the true positive, true negative, false positive, and false negative predictions.',
 '25_question': 'What is a confusion matrix and how is it used?',
 '26_answer': 'Regularization is a technique used to prevent overfitting by adding a penalty to the loss function for large coefficients, thus encouraging simpler models. Common regularization techniques include L1 and L2 regularization.',
 '26_question': 'What is regularization and why is it useful?',
 '27_answer': "A Receiver Operating Characteristic (ROC) curve is a graphical representation of a classification model's performance by plotting the true positive rate against the false positive rate at various threshold settings.",
 '27_question': 'What is a ROC curve?',
 '28_answer': 'Parametric models have a fixed number of parameters and make strong assumptions about the data distribution, while non-parametric models have a flexible number of parameters and make fewer assumptions about the data.',
 '28_question': 'What is the difference between parametric and non-parametric models?',
 '29_answer': 'The learning rate controls the size of the steps taken towards the minimum of the loss function in gradient descent. A small learning rate may result in slow convergence, while a large learning rate may cause divergence.',
 '29_question': 'What is the purpose of the learning rate in gradient descent?',
 '2_answer': 'Overfitting occurs when a model learns the training data too well, including noise and outliers, leading to poor generalization. It can be prevented by using techniques like cross-validation, regularization, and pruning.',
 '2_question': 'What is overfitting and how can it be prevented?',
 '30_answer': 'Ensemble learning is a technique that combines multiple models to improve overall performance. Common ensemble methods include bagging, boosting, and stacking.',
 '30_question': 'What is ensemble learning?',
 '31_answer': 'Type I error occurs when a true null hypothesis is incorrectly rejected, while type II error occurs when a false null hypothesis is not rejected.',
 '31_question': 'What is the difference between type I and type II errors?',
 '32_answer': 'A neural network is a series of algorithms that attempts to recognize underlying relationships in a set of data through a process that mimics the way the human brain operates.',
 '32_question': 'What is a neural network?',
 '33_answer': 'Backpropagation is a training algorithm for neural networks that calculates the gradient of the loss function and updates the weights to minimize the error.',
 '33_question': 'What is backpropagation?',
 '34_answer': 'A convolutional neural network (CNN) is a class of deep neural networks commonly used for analyzing visual imagery. It uses convolutional layers to detect patterns in images.',
 '34_question': 'What is a convolutional neural network (CNN)?',
 '35_answer': 'A recurrent neural network (RNN) is a class of neural networks designed to recognize patterns in sequences of data, such as time series or natural language.',
 '35_question': 'What is a recurrent neural network (RNN)?',
 '36_answer': 'Dropout is a regularization technique for neural networks that randomly drops units (along with their connections) from the network during training to prevent overfitting.',
 '36_question': 'What is dropout in neural networks?',
 '37_answer': 'The vanishing gradient problem occurs when gradients used in training deep neural networks become very small, making it difficult for the network to learn. This is especially problematic in deep networks with many layers.',
 '37_question': 'What is the vanishing gradient problem?',
 '38_answer': 'The exploding gradient problem occurs when gradients grow exponentially during training, causing the model parameters to become unstable and leading to poor performance.',
 '38_question': 'What is the exploding gradient problem?',
 '39_answer': 'L1 regularization adds the absolute value of the coefficients as a penalty term to the loss function, promoting sparsity. L2 regularization adds the squared value of the coefficients, promoting smaller weights.',
 '39_question': 'What is the difference between L1 and L2 regularization?',
 '3_answer': 'A confusion matrix is a table used to evaluate the performance of a classification model by comparing predicted and actual values.',
 '3_question': 'What is a confusion matrix?',
 '40_answer': 'Cross-entropy loss, also known as log loss, is a loss function commonly used in classification tasks. It measures the performance of a classification model by comparing the predicted probabilities with the actual class labels.',
 '40_question': 'What is cross-entropy loss?',
 '41_answer': "A validation set is used to tune the model and select hyperparameters during training, while a test set is used to evaluate the final model's performance on unseen data.",
 '41_question': 'What is the difference between a validation set and a test set?',
 '42_answer': 'A learning curve is a plot that shows the performance of a model over time or with respect to the amount of training data. It helps diagnose bias and variance issues.',
 '42_question': 'What is a learning curve?',
 '43_answer': 'Transfer learning is a technique where a model trained on one task is reused or adapted for a different but related task. It leverages pre-trained models to improve learning efficiency.',
 '43_question': 'What is transfer learning?',
 '44_answer': 'A random forest is an ensemble learning method that combines multiple decision trees to improve accuracy and reduce overfitting by averaging their predictions.',
 '44_question': 'What is a random forest?',
 '45_answer': 'Grid search exhaustively searches over a specified parameter grid, while random search samples parameter combinations randomly. Random search can be more efficient when dealing with a large parameter space.',
 '45_question': 'What is the difference between grid search and random search?',
 '46_answer': 'K-means is an unsupervised clustering algorithm that partitions data into k clusters by minimizing the within-cluster variance. It iteratively assigns data points to the nearest cluster centroid.',
 '46_question': 'What is the k-means algorithm?',
 '47_answer': "The elbow method is used to determine the optimal number of clusters in k-means clustering by plotting the within-cluster variance against the number of clusters and identifying the 'elbow' point.",
 '47_question': 'What is the elbow method in clustering?',
 '48_answer': 'Principal component analysis (PCA) is a dimensionality reduction technique that transforms high-dimensional data into a lower-dimensional space by finding the principal components that capture the most variance.',
 '48_question': 'What is a principal component analysis (PCA)?',
 '49_answer': 'Hyperparameter tuning is the process of selecting the best set of hyperparameters for a machine learning model to optimize its performance on a validation set.',
 '49_question': 'What is a hyperparameter tuning?',
 '4_answer': 'Precision is the ratio of true positive predictions to the total predicted positives, while recall is the ratio of true positive predictions to the total actual positives.',
 '4_question': 'What is the difference between precision and recall?',
 '50_answer': 'Long Short-Term Memory (LSTM) and Gated Recurrent Unit (GRU) are both types of recurrent neural networks (RNNs) designed to handle long-term dependencies. LSTMs have three gates (input, forget, and output), while GRUs have two gates (reset and update). GRUs are simpler and can be faster to train.',
 '50_question': 'What is the difference between LSTM and GRU?',
 '51_answer': 'Gradient clipping is used to prevent the exploding gradient problem by limiting the gradient values during backpropagation, ensuring stable training of neural networks.',
 '51_question': 'What is the purpose of gradient clipping?',
 '52_answer': 'A Bayesian network is a probabilistic graphical model that represents a set of variables and their conditional dependencies using a directed acyclic graph.',
 '52_question': 'What is a Bayesian network?',
 '53_answer': 'The softmax function is used in classification models to convert logits into probabilities, ensuring that the output values sum to 1.',
 '53_question': 'What is the purpose of using a softmax function?',
 '54_answer': 'A variational autoencoder (VAE) is a generative model that learns to represent input data in a latent space and generate new data samples by sampling from this latent space.',
 '54_question': 'What is a variational autoencoder (VAE)?',
 '55_answer': 'Batch gradient descent computes the gradient of the loss function using the entire training dataset, while stochastic gradient descent (SGD) computes the gradient using a single training example at each iteration. Mini-batch gradient descent is a compromise between the two.',
 '55_question': 'What is the difference between batch gradient descent and stochastic gradient descent?',
 '56_answer': "Data augmentation is used to increase the diversity of the training dataset by applying transformations such as rotations, translations, and flips, which helps improve the model's generalization performance.",
 '56_question': 'What is the purpose of data augmentation in machine learning?',
 '57_answer': 'Reinforcement learning is a type of machine learning where an agent learns to make decisions by taking actions in an environment to maximize cumulative rewards.',
 '57_question': 'What is reinforcement learning?',
 '58_answer': "Q-learning is an off-policy reinforcement learning algorithm that learns the value of the optimal policy independently of the agent's actions. SARSA is an on-policy algorithm that learns the value of the policy being followed by the agent.",
 '58_question': 'What is the difference between Q-learning and SARSA?',
 '59_answer': 'Dropout regularization is used to prevent overfitting in neural networks by randomly dropping units (neurons) and their connections during training, which encourages the network to learn robust features.',
 '59_question': 'What is the purpose of using dropout regularization?',
 '5_answer': 'Cross-validation is a technique for assessing how well a model generalizes to an independent dataset by dividing the data into training and validation subsets.',
 '5_question': 'What is cross-validation?',
 '60_answer': 'Transfer learning is a technique where a model trained on one task is reused or fine-tuned for a different but related task, leveraging pre-trained knowledge to improve learning efficiency and performance.',
 '60_question': 'What is the concept of transfer learning in machine learning?',
 '6_answer': 'Feature scaling is the process of normalizing or standardizing features to a similar scale, which is important for algorithms that are sensitive to the magnitude of features, such as gradient descent.',
 '6_question': 'What is feature scaling and why is it important?',
 '7_answer': "The bias-variance tradeoff is the balance between a model's ability to minimize errors on training data (bias) and its ability to generalize to new data (variance).",
 '7_question': 'What is the bias-variance tradeoff?',
 '8_answer': 'Gradient descent is an optimization algorithm used to minimize a function by iteratively moving in the direction of the steepest descent as defined by the negative of the gradient.',
 '8_question': 'What is gradient descent?',
 '9_answer': 'A hyperparameter is a parameter whose value is set before the learning process begins and controls the learning process itself, such as learning rate or the number of hidden layers in a neural network.',
 '9_question': 'What is a hyperparameter?'}