In [2]:
import pandas as pd
import requests

In [9]:
response = requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US&page=1')
response.json()

{'page': 1,
 'results': [{'adult': False,
   'backdrop_path': '/zfbjgQE1uSd9wiPTX4VzsLi0rGG.jpg',
   'genre_ids': [18, 80],
   'id': 278,
   'original_language': 'en',
   'original_title': 'The Shawshank Redemption',
   'overview': 'Imprisoned in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, where he puts his accounting skills to work for an amoral warden. During his long stretch in prison, Dufresne comes to be admired by the other inmates -- including an older prisoner named Red -- for his integrity and unquenchable sense of hope.',
   'popularity': 209.493,
   'poster_path': '/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg',
   'release_date': '1994-09-23',
   'title': 'The Shawshank Redemption',
   'video': False,
   'vote_average': 8.7,
   'vote_count': 27366},
  {'adult': False,
   'backdrop_path': '/tmU7GeKVybMWFButWEGl2M4GeiP.jpg',
   'genre_ids': [18, 80],
   'id': 238,
   'original_language': 'en',
   'original_title': 'The Godfather',
   'overview': 'Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the would-be killers, launching a campaign of bloody revenge.',
   'popularity': 206.903,
   'poster_path': '/3bhkrj58Vtu7enYsRolD1fZdja1.jpg',
   'release_date': '1972-03-14',
   'title': 'The Godfather',
   'video': False,
   'vote_average': 8.7,
   'vote_count': 20775},
  {'adult': False,
   'backdrop_path': '/kGzFbGhp99zva6oZODW5atUtnqi.jpg',
   'genre_ids': [18, 80],
   'id': 240,
   'original_language': 'en',
   'original_title': 'The Godfather Part II',
   'overview': 'In the continuing saga of the Corleone crime family, a young Vito Corleone grows up in Sicily and in 1910s New York. In the 1950s, Michael Corleone attempts to expand the family business into Las Vegas, Hollywood and Cuba.',
   'popularity': 108.2,
   'poster_path': '/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg',
   'release_date': '1974-12-20',
   'title': 'The Godfather Part II',
   'video': False,
   'vote_average': 8.6,
   'vote_count': 12534},
  {'adult': False,
   'backdrop_path': '/zb6fM1CX41D9rF9hdgclu0peUmy.jpg',
   'genre_ids': [18, 36, 10752],
   'id': 424,
   'original_language': 'en',
   'original_title': "Schindler's List",
   'overview': 'The true story of how businessman Oskar Schindler saved over a thousand Jewish lives from the Nazis while they worked as slaves in his factory during World War II.',
   'popularity': 89.964,
   'poster_path': '/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg',
   'release_date': '1993-12-15',
   'title': "Schindler's List",
   'video': False,
   'vote_average': 8.566,
   'vote_count': 15950},
  {'adult': False,
   'backdrop_path': '/bxgTSUenZDHNFerQ1whRKplrMKF.jpg',
   'genre_ids': [18],
   'id': 389,
   'original_language': 'en',
   'original_title': '12 Angry Men',
   'overview': "The defense and the prosecution have rested and the jury is filing into the jury room to decide if a young Spanish-American is guilty or innocent of murdering his father. What begins as an open and shut case soon becomes a mini-drama of each of the jurors' prejudices and preconceptions about the trial, the accused, and each other.",
   'popularity': 69.59,
   'poster_path': '/ow3wq89wM8qd5X7hWKxiRfsFf9C.jpg',
   'release_date': '1957-04-10',
   'title': '12 Angry Men',
   'video': False,
   'vote_average': 8.5,
   'vote_count': 8739},
  {'adult': False,
   'backdrop_path': '/m4TUa2ciEWSlk37rOsjiSIvZDXE.jpg',
   'genre_ids': [16, 10751, 14],
   'id': 129,
   'original_language': 'ja',
   'original_title': '千と千尋の神隠し',
   'overview': 'A young girl, Chihiro, becomes trapped in a strange new world of spirits. When her parents undergo a mysterious transformation, she must call upon the courage she never knew she had to free her family.',
   'popularity': 117.99,
   'poster_path': '/8i4s1mb3T3C0HHhSNR4nDMqRDgm.jpg',
   'release_date': '2001-07-20',
   'title': 'Spirited Away',
   'video': False,
   'vote_average': 8.5,
   'vote_count': 16608},
  {'adult': False,
   'backdrop_path': '/90ez6ArvpO8bvpyIngBuwXOqJm5.jpg',
   'genre_ids': [35, 18, 10749],
   'id': 19404,
   'original_language': 'hi',
   'original_title': 'दिलवाले दुल्हनिया ले जायेंगे',
   'overview': 'Raj is a rich, carefree, happy-go-lucky second generation NRI. Simran is the daughter of Chaudhary Baldev Singh, who in spite of being an NRI is very strict about adherence to Indian values. Simran has left for India to be married to her childhood fiancé. Raj leaves for India with a mission at his hands, to claim his lady love under the noses of her whole family. Thus begins a saga.',
   'popularity': 47.472,
   'poster_path': '/lfRkUr7DYdHldAqi3PwdQGBRBPM.jpg',
   'release_date': '1995-10-20',
   'title': 'Dilwale Dulhania Le Jayenge',
   'video': False,
   'vote_average': 8.5,
   'vote_count': 4448},
  {'adult': False,
   'backdrop_path': '/oOv2oUXcAaNXakRqUPxYq5lJURz.jpg',
   'genre_ids': [18, 28, 80, 53],
   'id': 155,
   'original_language': 'en',
   'original_title': 'The Dark Knight',
   'overview': 'Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker.',
   'popularity': 157.521,
   'poster_path': '/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
   'release_date': '2008-07-16',
   'title': 'The Dark Knight',
   'video': False,
   'vote_average': 8.5,
   'vote_count': 33067},
  {'adult': False,
   'backdrop_path': '/vxJ08SvwomfKbpboCWynC3uqUg4.jpg',
   'genre_ids': [14, 18, 80],
   'id': 497,
   'original_language': 'en',
   'original_title': 'The Green Mile',
   'overview': "A supernatural tale set on death row in a Southern prison, where gentle giant John Coffey possesses the mysterious power to heal people's ailments. When the cell block's head guard, Paul Edgecomb, recognizes Coffey's miraculous gift, he tries desperately to help stave off the condemned man's execution.",
   'popularity': 114.366,
   'poster_path': '/8VG8fDNiy50H4FedGwdSVUPoaJe.jpg',
   'release_date': '1999-12-10',
   'title': 'The Green Mile',
   'video': False,
   'vote_average': 8.506,
   'vote_count': 17566},
  {'adult': False,
   'backdrop_path': '/x6skktR5OS99lAX4JhmjCQYq490.jpg',
   'genre_ids': [35, 53, 18],
   'id': 496243,
   'original_language': 'ko',
   'original_title': '기생충',
   'overview': "All unemployed, Ki-taek's family takes peculiar interest in the wealthy and glamorous Parks for their livelihood until they get entangled in an unexpected incident.",
   'popularity': 113.675,
   'poster_path': '/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg',
   'release_date': '2019-05-30',
   'title': 'Parasite',
   'video': False,
   'vote_average': 8.505,
   'vote_count': 18399},
  {'adult': False,
   'backdrop_path': '/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg',
   'genre_ids': [53, 80],
   'id': 680,
   'original_language': 'en',
   'original_title': 'Pulp Fiction',
   'overview': "A burger-loving hit man, his philosophical partner, a drug-addled gangster's moll and a washed-up boxer converge in this sprawling, comedic crime caper. Their adventures unfurl in three stories that ingeniously trip back and forth in time.",
   'popularity': 96.414,
   'poster_path': '/vQWk5YBFWF4bZaofAbv0tShwBvQ.jpg',
   'release_date': '1994-09-10',
   'title': 'Pulp Fiction',
   'video': False,
   'vote_average': 8.488,
   'vote_count': 28046},
  {'adult': False,
   'backdrop_path': '/8x9iKH8kWA0zdkgNdpAew7OstYe.jpg',
   'genre_ids': [16, 10749, 18],
   'id': 372058,
   'original_language': 'ja',
   'original_title': '君の名は。',
   'overview': 'High schoolers Mitsuha and Taki are complete strangers living separate lives. But one night, they suddenly switch places. Mitsuha wakes up in Taki’s body, and he in hers. This bizarre occurrence continues to happen randomly, and the two must adjust their lives around each other.',
   'popularity': 98.903,
   'poster_path': '/vfJFJPepRKapMd5G2ro7klIRysq.jpg',
   'release_date': '2016-08-26',
   'title': 'Your Name.',
   'video': False,
   'vote_average': 8.5,
   'vote_count': 11446},
  {'adult': False,
   'backdrop_path': '/b3mdmjYTEL70j7nuXATUAD9qgu4.jpg',
   'genre_ids': [16, 14, 12],
   'id': 823219,
   'original_language': 'lv',
   'original_title': 'Straume',
   'overview': 'A solitary cat, displaced by a great flood, finds refuge on a boat with various species and must navigate the challenges of adapting to a transformed world together.',
   'popularity': 288.975,
   'poster_path': '/imKSymKBK7o73sajciEmndJoVkR.jpg',
   'release_date': '2024-08-29',
   'title': 'Flow',
   'video': False,
   'vote_average': 8.48,
   'vote_count': 441},
  {'adult': False,
   'backdrop_path': '/5JrZAtyk3LwiiAWLW0kwz41XZJC.jpg',
   'genre_ids': [12, 14, 28],
   'id': 122,
   'original_language': 'en',
   'original_title': 'The Lord of the Rings: The Return of the King',
   'overview': 'As armies mass for a final battle that will decide the fate of the world--and powerful, ancient forces of Light and Dark compete to determine the outcome--one member of the Fellowship of the Ring is revealed as the noble heir to the throne of the Kings of Men. Yet, the sole hope for triumph over evil lies with a brave hobbit, Frodo, who, accompanied by his loyal friend Sam and the hideous, wretched Gollum, ventures deep into the very dark heart of Mordor on his seemingly impossible quest to destroy the Ring of Power.\u200b',
   'popularity': 152.378,
   'poster_path': '/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg',
   'release_date': '2003-12-17',
   'title': 'The Lord of the Rings: The Return of the King',
   'video': False,
   'vote_average': 8.5,
   'vote_count': 24356},
  {'adult': False,
   'backdrop_path': '/mzfx54nfDPTUXZOG48u4LaEheDy.jpg',
   'genre_ids': [35, 18, 10749],
   'id': 13,
   'original_language': 'en',
   'original_title': 'Forrest Gump',
   'overview': 'A man with a low IQ has accomplished great things in his life and been present during significant historic events—in each case, far exceeding what anyone imagined he could do. But despite all he has achieved, his one true love eludes him.',
   'popularity': 91.026,
   'poster_path': '/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg',
   'release_date': '1994-06-23',
   'title': 'Forrest Gump',
   'video': False,
   'vote_average': 8.5,
   'vote_count': 27572},
  {'adult': False,
   'backdrop_path': '/x4biAVdPVCghBlsVIzB6NmbghIz.jpg',
   'genre_ids': [37],
   'id': 429,
   'original_language': 'it',
   'original_title': 'Il buono, il brutto, il cattivo',
   'overview': 'While the Civil War rages on between the Union and the Confederacy, three men – a quiet loner, a ruthless hitman, and a Mexican bandit – comb the American Southwest in search of a strongbox containing $200,000 in stolen gold.',
   'popularity': 79.445,
   'poster_path': '/bX2xnavhMYjWDoZp1VM6VnU1xwe.jpg',
   'release_date': '1966-12-22',
   'title': 'The Good, the Bad and the Ugly',
   'video': False,
   'vote_average': 8.465,
   'vote_count': 8681},
  {'adult': False,
   'backdrop_path': '/sJNNMCc6B7KZIY3LH3JMYJJNH5j.jpg',
   'genre_ids': [28, 18],
   'id': 346,
   'original_language': 'ja',
   'original_title': '七人の侍',
   'overview': "A samurai answers a village's request for protection after he falls on hard times. The town needs protection from bandits, so the samurai gathers six others to help him teach the people how to defend themselves, and the villagers provide the soldiers with food.",
   'popularity': 49.499,
   'poster_path': '/iAq0sq42vKTLneVGqHn1D4GzgrM.jpg',
   'release_date': '1954-04-26',
   'title': 'Seven Samurai',
   'video': False,
   'vote_average': 8.5,
   'vote_count': 3718},
  {'adult': False,
   'backdrop_path': '/dlC0ed9Ugh3FzydnkBtV5lRXUu4.jpg',
   'genre_ids': [16, 18, 10752],
   'id': 12477,
   'original_language': 'ja',
   'original_title': '火垂るの墓',
   'overview': 'In the final months of World War II, 14-year-old Seita and his sister Setsuko are orphaned when their mother is killed during an air raid in Kobe, Japan. After a falling out with their aunt, they move into an abandoned bomb shelter. With no surviving relatives and their emergency rations depleted, Seita and Setsuko struggle to survive.',
   'popularity': 0.054,
   'poster_path': '/k9tv1rXZbOhH7eiCk378x61kNQ1.jpg',
   'release_date': '1988-04-16',
   'title': 'Grave of the Fireflies',
   'video': False,
   'vote_average': 8.5,
   'vote_count': 5598},
  {'adult': False,
   'backdrop_path': '/7TF4p86ZafnxFuNqWdhpHXFO244.jpg',
   'genre_ids': [18, 80],
   'id': 769,
   'original_language': 'en',
   'original_title': 'GoodFellas',
   'overview': 'The true story of Henry Hill, a half-Irish, half-Sicilian Brooklyn kid who is adopted by neighbourhood gangsters at an early age and climbs the ranks of a Mafia family under the guidance of Jimmy Conway.',
   'popularity': 78.61,
   'poster_path': '/aKuFiU82s5ISJpGZp7YkIr3kCUd.jpg',
   'release_date': '1990-09-12',
   'title': 'GoodFellas',
   'video': False,
   'vote_average': 8.5,
   'vote_count': 12944},
  {'adult': False,
   'backdrop_path': '/zoVeIgKzGJzpdG6Gwnr7iOYfIMU.jpg',
   'genre_ids': [18, 10749],
   'id': 11216,
   'original_language': 'it',
   'original_title': 'Nuovo Cinema Paradiso',
   'overview': "A filmmaker recalls his childhood, when he fell in love with the movies at his village's theater and formed a deep friendship with the theater's projectionist.",
   'popularity': 37.942,
   'poster_path': '/gCI2AeMV4IHSewhJkzsur5MEp6R.jpg',
   'release_date': '1988-11-17',
   'title': 'Cinema Paradiso',
   'video': False,
   'vote_average': 8.451,
   'vote_count': 4394}],
 'total_pages': 492,
 'total_results': 9839}

In [12]:
pd.DataFrame(response.json()['results']).head()

,adult,backdrop_path,genre_ids,id,original_language,original_title,overview,popularity,poster_path,release_date,title,video,vote_average,vote_count
0,False,/zfbjgQE1uSd9wiPTX4VzsLi0rGG.jpg,"[18, 80]",278,en,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,209.493,/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg,1994-09-23,The Shawshank Redemption,False,8.700,27366
1,False,/tmU7GeKVybMWFButWEGl2M4GeiP.jpg,"[18, 80]",238,en,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",206.903,/3bhkrj58Vtu7enYsRolD1fZdja1.jpg,1972-03-14,The Godfather,False,8.700,20775
2,False,/kGzFbGhp99zva6oZODW5atUtnqi.jpg,"[18, 80]",240,en,The Godfather Part II,In the continuing saga of the Corleone crime f...,108.200,/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg,1974-12-20,The Godfather Part II,False,8.600,12534
3,False,/zb6fM1CX41D9rF9hdgclu0peUmy.jpg,"[18, 36, 10752]",424,en,Schindler's List,The true story of how businessman Oskar Schind...,89.964,/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg,1993-12-15,Schindler's List,False,8.566,15950
4,False,/bxgTSUenZDHNFerQ1whRKplrMKF.jpg,[18],389,en,12 Angry Men,The defense and the prosecution have rested an...,69.590,/ow3wq89wM8qd5X7hWKxiRfsFf9C.jpg,1957-04-10,12 Angry Men,False,8.500,8739

In [8]:
temp_df = pd.DataFrame(response.json()['results'])[['id','title','overview','release_date','popularity','vote_average','vote_count']]
temp_df

,id,title,overview,release_date,popularity,vote_average,vote_count
0,278,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,1994-09-23,209.493,8.700,27366
1,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,206.903,8.700,20775
2,240,The Godfather Part II,In the continuing saga of the Corleone crime f...,1974-12-20,108.200,8.600,12534
3,424,Schindler's List,The true story of how businessman Oskar Schind...,1993-12-15,89.964,8.566,15950
4,389,12 Angry Men,The defense and the prosecution have rested an...,1957-04-10,69.590,8.500,8739
5,129,Spirited Away,"A young girl, Chihiro, becomes trapped in a st...",2001-07-20,117.990,8.500,16608
6,19404,Dilwale Dulhania Le Jayenge,"Raj is a rich, carefree, happy-go-lucky second...",1995-10-20,47.472,8.500,4448
7,155,The Dark Knight,Batman raises the stakes in his war on crime. ...,2008-07-16,157.521,8.500,33067
8,497,The Green Mile,A supernatural tale set on death row in a Sout...,1999-12-10,114.366,8.506,17566
9,496243,Parasite,"All unemployed, Ki-taek's family takes peculia...",2019-05-30,113.675,8.505,18399
10,680,Pulp Fiction,"A burger-loving hit man, his philosophical par...",1994-09-10,96.414,8.488,28046
11,372058,Your Name.,High schoolers Mitsuha and Taki are complete s...,2016-08-26,98.903,8.500,11446
12,823219,Flow,"A solitary cat, displaced by a great flood, fi...",2024-08-29,288.975,8.480,441
13,122,The Lord of the Rings: The Return of the King,As armies mass for a final battle that will de...,2003-12-17,152.378,8.500,24356
14,13,Forrest Gump,A man with a low IQ has accomplished great thi...,1994-06-23,91.026,8.500,27572
15,429,"The Good, the Bad and the Ugly",While the Civil War rages on between the Union...,1966-12-22,79.445,8.465,8681
16,346,Seven Samurai,A samurai answers a village's request for prot...,1954-04-26,49.499,8.500,3718
17,12477,Grave of the Fireflies,"In the final months of World War II, 14-year-o...",1988-04-16,0.054,8.500,5598
18,769,GoodFellas,"The true story of Henry Hill, a half-Irish, ha...",1990-09-12,78.610,8.500,12944
19,11216,Cinema Paradiso,"A filmmaker recalls his childhood, when he fel...",1988-11-17,37.942,8.451,4394

In [3]:
df = pd.DataFrame()
df

Empty DataFrame
Columns: []
Index: []

In [19]:
for i in range(1,429):
    response = requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US&page={}'.format(i))
    temp_df = pd.DataFrame(response.json()['results'])[['id','title','overview','release_date','popularity','vote_average','vote_count']]
    df = df.append(temp_df,ignore_index=True)

In [21]:
df

,id,title,overview,release_date,popularity,vote_average,vote_count
0,19404,Dilwale Dulhania Le Jayenge,"Raj is a rich, carefree, happy-go-lucky second...",1995-10-20,18.433,8.7,2763
1,724089,Gabriel's Inferno Part II,Professor Gabriel Emerson finally learns the t...,2020-07-31,8.439,8.7,1223
2,278,The Shawshank Redemption,Framed in the 1940s for the double murder of h...,1994-09-23,65.570,8.7,18637
3,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,63.277,8.7,14052
4,761053,Gabriel's Inferno Part III,The final part of the film adaption of the ero...,2020-11-19,26.691,8.7,773
...,...,...,...,...,...,...,...
8546,13805,Disaster Movie,"The filmmaking team behind the hits ""Scary Mov...",2008-08-29,14.630,3.2,714
8547,5491,Battlefield Earth,"In the year 3000, man is no match for the Psyc...",2000-05-12,10.647,3.0,543
8548,14164,Dragonball Evolution,The young warrior Son Goku sets out on a quest...,2009-03-12,32.244,2.8,1447
8549,11059,House of the Dead,"Set on an island off the coast, a techno rave ...",2003-04-11,14.502,2.8,238
8550,40016,Birdemic: Shock and Terror,A platoon of eagles and vultures attacks the r...,2010-02-27,9.824,2.2,215

In [22]:
df.shape

(8551, 7)

In [23]:
df.to_csv('movies.csv')